name: Update Chart Version

on:
  workflow_dispatch:

jobs:
  update_chart_version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Fetch latest release tag
      run: |
        curl -s https://api.github.com/repos/ahmetb/kubectx/releases/latest \
        | jq -r '.tag_name' \
        | sed 's/^v//' \
        > latest_release_tag.txt

    - name: Update chart.yaml
      run: |
        LATEST_RELEASE_TAG=$(cat latest_release_tag.txt)
        CURRENT_APP_VERSION=$(grep -E "^appVersion:" chart.yaml | awk '{print $2}')
        if [[ "$CURRENT_APP_VERSION" != "$LATEST_RELEASE_TAG" ]]; then
          sed -i "s/^appVersion:.*/appVersion: v$LATEST_RELEASE_TAG/" chart.yaml
        else
          echo "appVersion in chart.yaml is already up-to-date with the latest release tag. Skipping update."
          exit 0
        fi

    - name: Print updated chart.yaml
      run: cat chart.yaml
      

    - name: Commit changes
      run: |
        git status
        git config --local user.email "Aakanksha"
        git config --local user.name "aakankshasingh1223@gmail.com"
        git add .
        git diff-index --quiet HEAD || git commit -m "Update appVersion in chart.yaml" chart.yaml
        git push
