name: Update Chart Version

on:
  push:
    branches:
      - releasetag
  workflow_dispatch:

jobs:
  update_chart_version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Fetch latest release tag
      run: |
        curl -s https://api.github.com/repos/ahmetb/kubectx/releases/latest \
        | jq -r '.tag_name' \
        | sed 's/^v//' \
        > latest_release_tag.txt

    - name: Update chart.yaml
      run: |
        LATEST_RELEASE_TAG=$(cat latest_release_tag.txt)
        sed -i "s/^appVersion:.*/appVersion: $LATEST_RELEASE_TAG/" chart.yaml

    - name: Print updated chart.yaml
      run: cat chart.yaml

    - name: Commit changes
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git commit -m "Update appVersion in chart.yaml" chart.yaml
        git push
