name: Fetch Latest Release Tag and Update Chart

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  fetch-tag-and-update-chart:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repositories
      uses: actions/checkout@v2
      
    - name: Fetch latest release tag
      run: |
        latest_tag=$(curl -s https://api.github.com/repos/ahmetb/kubectx/releases/latest | grep -oP '"tag_name": "\K(.*?)(?=")')
        echo "latest_tag=$latest_tag" >> $GITHUB_ENV
        
    - name: Update appVersion in chart.yaml
      run: |
        latest_tag=$latest_tag
        sed -i "s/appVersion:.*/appVersion: $latest_tag/" ./chart.yaml
        
    - name: Commit changes
      run: |
        git config user.name "Your Name"
        git config user.email "you@example.com"
        git add chart.yaml
        git commit -m "Update appVersion to $latest_tag"
        git push
