name: Fetch Latest Release Tag and Update Chart

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  fetch-tag-and-update-chart:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repositories
      uses: actions/checkout@v2
      
    - name: Fetch latest release tag
      run: |
        latest_tag=$(curl -s https://api.github.com/repos/ahmetb/kubectx/releases/latest | grep -oP '"tag_name": "\K(.*?)(?=")')
        echo "latest_tag=$latest_tag" >> $GITHUB_OUTPUT
        echo "latest_tag=$latest_tag" >> $GITHUB_STATE

        
        
#     - name: Update appVersion in chart.yaml
#       run: |
#         latest_tag=${{ steps.fetch-tag-and-update-chart.outputs.latest_tag }}
#         sed -i "s/appVersion:.*/appVersion: $latest_tag/" chart.yaml
        
    - name: Update Chart.yaml
      working-directory: ${{ github.event.client_payload.domain_service }}
      run: |
        cat <<EOF > Chart.yaml
        apiVersion: v2
        name: ${{ github.event.client_payload.domain_service }}
        version: ${{ steps.version-bump.outputs.newTag }}
        version: '${{ github.event.client_payload.app_version }}'
        appVersion: ${{ steps.fetch-tag-and-update-chart.outputs.latest_tag }}
        EOF

        
    - name: Commit changes
      run: |
        git config user.name "Aakanksha"
        git config user.email "aakankshasingh1223@gmail.com"
        git add chart.yaml
        git commit -m "Update appVersion to $latest_tag"
        git push
