name: Fetch Latest Release Tag

on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  fetch-latest-release-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Fetch latest release tag
        id: latest_tag
        run: echo ::set-output name=tag::$(git describe --tags --abbrev=0)
      - name: Print latest release tag
        run: echo "Latest release tag is ${{ steps.latest_tag.outputs.tag }}"
